apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: default
data:
  app.conf: |-
    upstream backend {
      server web;
    }
    server {
      listen 80;
      location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
      }
    }    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
     app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d 
      volumes:     
      - name: config
        configMap:
          name: proxy-config 
---     
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  ports:
  - name: http
    port: 80
    targetPort: http   
  type: NodePort